#!/usr/bin/env python3
"""
Run inference with a trained Detectron2 Mask R-CNN model over a directory of images.

Usage:
    python predict.py [--config CONFIG_PATH]

For each image found in directories.test_image_dir (matching the rgb filename
pattern in settings.filename_patterns), this writes:
  - an overlay image with masks/boxes to directories.prediction_output_dir/predicted_images/
  - a COCO-format prediction JSON to directories.prediction_json_dir (if set)

If a matching depth image (matching the depth filename pattern) is found next
to the rgb image, RGB-D inference is used; otherwise RGB-only inference is used.

Requires files.test_metadata_catalog_file and files.train_dataset_catalog_file
to exist - these are generated by train.py during dataset registration.

After all images are processed, also writes:
  - directories.prediction_json_dir/annotations.json  (merged COCO annotation file)
  - directories.prediction_output_dir/images.zip      (original images, ready for CVAT upload)
"""
import argparse
import datetime
import json
import logging
import os
import sys
import traceback
import zipfile

import cv2
import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), 'fruit_detector'))

from utils.utils import load_config
from detectron_predictor.detectron_predictor import DetectronPredictor


def _build_merged_coco(image_entries, template_dict):
    """Merge per-image COCO prediction dicts into a single dataset-level annotation file.

    image_entries: list of (sample_no, filename, json_dict, height, width)
    template_dict: any per-image json_dict, used to copy info/license/categories structure
    """
    merged_images = []
    merged_annotations = []
    merged_confidence = []
    ann_id = 1

    for sample_no, filename, json_dict, h, w in image_entries:
        merged_images.append({
            'id': sample_no,
            'file_name': filename,
            'width': w,
            'height': h,
            'date_captured': datetime.datetime.now(datetime.timezone.utc).isoformat(' '),
        })
        for ann in json_dict.get('annotations', []):
            ann_copy = dict(ann)
            ann_copy['id'] = ann_id
            ann_copy['image_id'] = sample_no
            merged_annotations.append(ann_copy)
            ann_id += 1
        for conf in json_dict.get('confidence', []):
            conf_copy = dict(conf)
            conf_copy['image_id'] = sample_no
            merged_confidence.append(conf_copy)

    merged = {}
    for key, val in template_dict.items():
        if key == 'images':
            merged[key] = merged_images
        elif key == 'annotations':
            merged[key] = merged_annotations
        elif key == 'confidence':
            # merged[key] = merged_confidence
            pass  # don't include confidence in merged file for COCO 1.0 format compatibility
        else:
            merged[key] = val
    return merged


def main():
    parser = argparse.ArgumentParser(description='Run inference over a directory of images')
    parser.add_argument('--config', default=None, help='Path to params.yaml (defaults to ./config/params.yaml)')
    args = parser.parse_args()

    config_data = load_config(args.config)

    test_image_dir = config_data['directories']['test_image_dir']
    prediction_output_dir = config_data['directories']['prediction_output_dir']
    prediction_json_dir = config_data['directories']['prediction_json_dir']

    rgb_pattern = config_data['settings']['filename_patterns']['rgb']
    depth_pattern = config_data['settings']['filename_patterns']['depth']

    if prediction_json_dir:
        os.makedirs(prediction_json_dir, exist_ok=True)
    os.makedirs(prediction_output_dir, exist_ok=True)

    all_files = sorted([
        f for f in os.listdir(test_image_dir)
        if os.path.isfile(os.path.join(test_image_dir, f))
    ])
    rgb_files = sorted([f for f in all_files if rgb_pattern in f])
    depth_files = set(f for f in all_files if depth_pattern in f)

    print(f"Found {len(rgb_files)} image(s) in '{test_image_dir}'")

    predictor = DetectronPredictor(config_data)

    # (sample_no, original_filename, json_dict, height, width)
    image_entries = []

    for sample_no, rgb_file in enumerate(rgb_files, start=1):
        image_file_name = os.path.join(test_image_dir, rgb_file)
        filename, _ = os.path.splitext(rgb_file)

        prediction_json_output_file = ''
        if prediction_json_dir:
            prediction_json_output_file = os.path.join(prediction_json_dir, filename) + '.json'

        depth_candidate = rgb_file.replace(rgb_pattern, depth_pattern, 1)

        try:
            if depth_candidate in depth_files:
                rgb_image = cv2.imread(image_file_name)
                depth_image = cv2.imread(os.path.join(test_image_dir, depth_candidate), cv2.IMREAD_UNCHANGED)
                rgbd_image = np.dstack((rgb_image, depth_image))
                result = predictor.get_predictions_image(
                    rgbd_image, prediction_json_output_file, prediction_output_dir,
                    image_file_name, sample_no)
            else:
                rgb_image = cv2.imread(image_file_name)
                result = predictor.get_rgb_predictions_image(
                    rgb_image, prediction_json_output_file, prediction_output_dir,
                    image_file_name, sample_no)
            h, w = rgb_image.shape[:2]
            image_entries.append((sample_no, rgb_file, result[0], h, w))
        except Exception as e:
            logging.error(e)
            print(traceback.format_exc())

    # --- merged annotation file (all images in one COCO JSON) ---
    if prediction_json_dir and image_entries:
        template_dict = image_entries[0][2]
        merged = _build_merged_coco(image_entries, template_dict)
        merged_path = os.path.join(prediction_json_dir, 'annotations.json')
        with open(merged_path, 'w') as f:
            json.dump(merged, f, indent=2)
        print(f"Merged annotation file saved to {merged_path}")

    # --- zip original images for CVAT upload ---
    zip_path = os.path.join(prediction_output_dir, 'images.zip')
    with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zf:
        for rgb_file in rgb_files:
            zf.write(os.path.join(test_image_dir, rgb_file), rgb_file)
    print(f"Original images zipped to {zip_path}")


if __name__ == '__main__':
    main()
