#!/usr/bin/env python3
"""
Run inference with a trained Detectron2 Mask R-CNN model over a directory of images.

Usage:
    python predict.py [--config CONFIG_PATH]

For each image found in directories.test_image_dir (matching the rgb filename
pattern in settings.filename_patterns), this writes:
  - an overlay image with masks/boxes to directories.prediction_output_dir/predicted_images/
  - a COCO-format prediction JSON to files.prediction_json_dir (if set)

If a matching depth image (matching the depth filename pattern) is found next
to the rgb image, RGB-D inference is used; otherwise RGB-only inference is used.

Requires files.test_metadata_catalog_file and files.train_dataset_catalog_file
to exist - these are generated by train.py during dataset registration.
"""
import argparse
import logging
import os
import sys
import traceback

import cv2
import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), 'fruit_detector'))

from utils.utils import load_config
from detectron_predictor.detectron_predictor import DetectronPredictor
from detectron_predictor.json_writer.pycococreator.pycococreatortools.fruit_orientation import FruitTypes


def main():
    parser = argparse.ArgumentParser(description='Run inference over a directory of images')
    parser.add_argument('--config', default=None, help='Path to params.yaml (defaults to ./config/params.yaml)')
    args = parser.parse_args()

    config_data = load_config(args.config)

    test_image_dir = config_data['directories']['test_image_dir']
    prediction_output_dir = config_data['directories']['prediction_output_dir']
    prediction_json_dir = config_data['directories']['prediction_json_dir']

    rgb_pattern = config_data['settings']['filename_patterns']['rgb']
    depth_pattern = config_data['settings']['filename_patterns']['depth']

    fruit_type_name = config_data['settings']['fruit_type'].upper()
    fruit_type = FruitTypes.Tomato if fruit_type_name == 'TOMATO' else FruitTypes.Strawberry

    if prediction_json_dir:
        os.makedirs(prediction_json_dir, exist_ok=True)

    all_files = sorted([
        f for f in os.listdir(test_image_dir)
        if os.path.isfile(os.path.join(test_image_dir, f))
    ])
    rgb_files = sorted([f for f in all_files if rgb_pattern in f])
    depth_files = set(f for f in all_files if depth_pattern in f)

    print(f"Found {len(rgb_files)} image(s) in '{test_image_dir}'")

    predictor = DetectronPredictor(config_data)

    for sample_no, rgb_file in enumerate(rgb_files, start=1):
        image_file_name = os.path.join(test_image_dir, rgb_file)
        filename, _ = os.path.splitext(rgb_file)

        prediction_json_output_file = ''
        if prediction_json_dir:
            prediction_json_output_file = os.path.join(prediction_json_dir, filename) + '.json'

        depth_candidate = rgb_file.replace(rgb_pattern, depth_pattern, 1)

        try:
            if depth_candidate in depth_files:
                rgb_image = cv2.imread(image_file_name)
                depth_image = cv2.imread(os.path.join(test_image_dir, depth_candidate), cv2.IMREAD_UNCHANGED)
                rgbd_image = np.dstack((rgb_image, depth_image))
                predictor.get_predictions_image(
                    rgbd_image, prediction_json_output_file, prediction_output_dir,
                    image_file_name, sample_no, fruit_type)
            else:
                rgb_image = cv2.imread(image_file_name)
                predictor.get_rgb_predictions_image(
                    rgb_image, prediction_json_output_file, prediction_output_dir,
                    image_file_name, sample_no, fruit_type)
        except Exception as e:
            logging.error(e)
            print(traceback.format_exc())


if __name__ == '__main__':
    main()
